sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.login=sqa_b45a066aef593ca2d9a6cf9263c3cca24c04c668
sonar.exclusions=tests/**,*.pyc,__pycache__/**